baseURL = "https://anriclee.github.io/"
languageCode = "en-us"
title = "AnricLee's House"
theme = "barn"
copyright = "Copyright &copy; <a href=\"https://github.com/anriclee\"> AnricLee's Blog </a>"
# disqusShortname = 'yourDisqusShortname'

[params.highlight]
  style = "agate"
#   style = "vs2015"

[params.share]
  enabled = "true"

# items num shown in every page
paginate = 10

[[ params.social ]]
    url = "https://github.com/anriclee"
    fa_icon  = "fab fa-github"

[[ params.social ]]
    url = "https://www.linkedin.com"
    fa_icon  = "fab fa-telegram"

[[ params.social ]]
    url = "https://twitter.com"
    fa_icon  = "fab fa-twitter"

[[ params.social ]]
    url = "https://anriclee.github.io/index.xml"
    fa_icon  = "fa fa-rss"