baseURL = "https://anriclee.github.io/"
languageCode = "en-us"
title = "AnricLee's House"
theme = "barn"
copyright = "&copy; <a href=\"https://github.com/anriclee\"> AnricLee </a>"

# items num shown in every page
paginate = 10

[[ params.social ]]
    url = "about"
    fa_icon  = "fas fa-info"

[[ params.social ]]
    url = "https://github.com/anriclee"
    fa_icon  = "fab fa-github"

[[ params.social ]]
    url = "https://www.linkedin.com"
    fa_icon  = "fab fa-weixin"

[[ params.social ]]
    url = "https://twitter.com"
    fa_icon  = "fab fa-weibo"